/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bd1.obli2012.main;

import bd1.obli2012.main.arbol.TableTreeNode;
import bd1.obli2012.main.arbol.AttributeTreeNode;
import bd1.obli2012.framework.Attribute;
import bd1.obli2012.framework.Database;
import bd1.obli2012.framework.DatabaseManager;
import bd1.obli2012.framework.Table;
import bd1.obli2012.main.arbol.DBTreeCellRenderer;
import bd1.obli2012.main.arbol.DBTreeNode;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author guillermo
 */
public class MainFrame extends javax.swing.JFrame implements TreeSelectionListener{

    private JTree arbolBD;
    private JPanel tablePanel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //Colocamos el nuevo tipo de layout que queremos que tenga nuestro JFrame
        this.setLayout(new FlowLayout());
        this.pack();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        /* inicializamos el arbol */
        arbolBD = cargarArbol();
        treePanel = new JScrollPane(arbolBD);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        treePanel.setMinimumSize(new java.awt.Dimension(120, 90));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(treePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(treePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }
             }*/
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane treePanel;
    // End of variables declaration//GEN-END:variables

    private JTree cargarArbol() {

        List<Database> dbs = DatabaseManager.getInstance().getDataBases();
        DefaultMutableTreeNode dbRoot = new DefaultMutableTreeNode("Bases de datos");

        for (Database db : dbs) {
            DBTreeNode dbNode = new DBTreeNode(db);
            for (Table t : db.getTables()) {
                TableTreeNode tableNode = new TableTreeNode(db, t);
                for (Attribute a : t.getAttributes()) {
                    AttributeTreeNode atn = new AttributeTreeNode(a);
                    tableNode.add(atn);
                }
                dbNode.add(tableNode);
            }
            dbRoot.add(dbNode);
        }
    
    JTree dbTree = new JTree(dbRoot);
    dbTree.addTreeSelectionListener(this);
    dbTree.setCellRenderer (
    new DBTreeCellRenderer());
        return dbTree ;
}

    public void valueChanged(TreeSelectionEvent tse) {
        Object selectedNode = arbolBD.getLastSelectedPathComponent();
        if(selectedNode instanceof TableTreeNode) {
            TableTreeNode tn = (TableTreeNode)selectedNode;
            
            if(tablePanel != null){
                this.remove(tablePanel);
            }
            tablePanel  = new PanelTabla(tn.getDatabase(), tn.getTable().getNombre());
            this.add(tablePanel, BorderLayout.EAST);
            this.pack();
        }
        
        
       
    }
}
